### ISSUE TITLE
https://ghs.champonthis.de cannot connect to server on same wifi network

### ISSUE THREAD

**Issue by JefStat** [Lurkars/ghs-server#12]
https://ghs.champonthis.de is connecting to a server on the same computer but trying to connect from my phone is not working and the follow exception is observed.

```
023-02-23 15:23:33 java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030x060x830xbc0x7fV0xe00x1f0xb50x1d0xca0x0a0xed0xc7Byvm0xa650xb30xfd0xc00xa6%n0xe5X0xb950xe2!0xac ]. HTTP method names must be tokens
2023-02-23 15:23:33     at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.71.jar!/:na]
2023-02-23 15:23:33     at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

Additionally my phone can open the server page.

**Comment by Lurkars** [comment]
This looks like connect with secure option to unsecure server or vice versa. But in general I will need some more information: How is your server setup? Are you connecting from local IP and what did you enter on your phone under server connection settings? Always try to provider as much information as you can to describe a problem.

**Comment by JefStat** [comment]
- Ran from the docker image with the following command
`docker run --rm -d -p 8080:8080 -v /Users/.../projects/frosthaven:/root/.ghs --name ghs-server gloomhavensecretariat/ghs-server`, 
- tried setting `ghs-server.public=true` and without
- Trying the secure checkbox opens a new tab to https://192.168.1.2:8080 that doesn't load


Comment aside I see from the documentation that I was supposed to use `server.ssl.enabled=true` and the secure flag to connect on the same network. I see that the lastest client is pulled automatically and served.

**Comment by Lurkars** [comment]
So you solved this yourself now?!

**Comment by JefStat** [comment]
Yeah. User error. RTFM ¯\_(ツ)_/¯
